CREATE USER enervision_app;

GRANT CONNECT ON DATABASE enervision TO enervision_app;
GRANT USAGE ON SCHEMA ener TO enervision_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ener TO enervision_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ener GRANT SELECT, INSERT, UPDATE ON TABLES TO enervision_app;
