CREATE USER enervision;

GRANT CONNECT ON DATABASE enervision TO enervision;
GRANT USAGE ON SCHEMA ener TO enervision;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ener TO enervision;
ALTER DEFAULT PRIVILEGES IN SCHEMA ener GRANT SELECT, INSERT, UPDATE ON TABLES TO enervision;
