services:
  core:
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.local

  frontend:
    volumes:
      - ./frontend:/frontend

  worker-ingestion:
    volumes:
      - ./backend/workeringestion:/backend/workeringestion

  etl:
    env_file:
      - .env.local

  prediction:
    environment:
      DVC_PUSH: "0"
    env_file:
      - .env.local

networks:
  enervision_network:
    external: true
    name: enervision_network